name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI_BUILD: 1

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Run Build Tests
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        cd scripts
        .\test_build.bat

    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          build/Testing/Temporary/LastTest.log
          build/*.log
